In [1]:
import pandas as pd 
import numpy as np 


Predict the prices of the properties based on the features available to us

In [2]:
#data available with us
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


Now our input x variables are area_sqft and bedrooms and our target variable y is price 

In [3]:
#shuffle data 
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

#train test split 
split_index = int(0.75 * len(df))

#75 % train 25 % test data split
train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

X_train = train_df[["area_sqft","bedrooms"]]
y_train = train_df["price"]

X_test = test_df[["area_sqft","bedrooms"]]
y_test = test_df["price"]



In [4]:
#Fitting a linear regression model 
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)


LinearRegression()

In [5]:
#Intercept part
print("Intercept:",model.intercept_)
print("Coefficient:",model.coef_)

Intercept: -8.74573378839591
Coefficient: [ 0.11023891 -1.15187713]


In [6]:
y_pred = model.predict(X_test)

result = pd.DataFrame({
"Actual":y_test.values,
"Predicted":y_pred
})

result

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [7]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print("MAE :",mae)

MAE : 7.133105802047773


In [8]:
#Revision 1 
import pandas as pd
import numpy as np


In [9]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [10]:
#Train test split 75 25 split

#random shuffling
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]


In [11]:
#Fitting the model using linear regression
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [12]:
results = pd.DataFrame({
    "Actual":y_test,
    "Predicted":y_pred
})

results

,Actual,Predicted
6,90,99.189420
7,180,185.076792


In [13]:
#Coffiecient and intercept
#y = mx + c
print("Coefficient",model.coef_)
print("Intercept :",model.intercept_)

Coefficient [ 0.11023891 -1.15187713]
Intercept : -8.74573378839591


In [14]:
#Checking the error metrics
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773


In [15]:
#Fitting separate models on area sqft and bedrooms
X_train_area = df_train[["area_sqft"]]
y_train_area = df_train["price"]

X_test_area = df_test[["area_sqft"]]
y_test_area = df_test["price"]

area_model = model.fit(X_train_area,y_train_area)

area_model_pred = model.predict(X_test_area)

mae_area = mean_absolute_error(y_test_area,area_model_pred)


results_area = pd.DataFrame({
    "Model Name": "Price predict w Area",
    "Actual":y_test.values,
    "Predicted":area_model_pred,
    "MAE":mae_area
})

print(results_area)




print(f"MAE on area : {mae_area}")


             Model Name  Actual   Predicted       MAE
0  Price predict w Area      90   99.081847  7.229801
1  Price predict w Area     180  185.377754  7.229801
MAE on area : 7.229800629590763


In [16]:
#Fitting the model on bedrooms only
X_train_b = df_train[["bedrooms"]]
y_train_b = df_train["price"]

X_test_b = df_test[["bedrooms"]]
y_test_b = df_test["price"]

model_b = model.fit(X_train_b,y_train_b)

y_pred_b = model_b.predict(X_test_b)

mae_b = mean_absolute_error(y_test_b,y_pred_b)
#result
results_b = pd.DataFrame({
    "Model Name": "Price predict w Bedrooms",
    "Actual":y_test_b.values,
    "Predicted":y_pred_b,
    "MAE":mae_b
})

results_b

,Model Name,Actual,Predicted,MAE
0,Price predict w Bedrooms,90,95.681818,8.636364
1,Price predict w Bedrooms,180,191.590909,8.636364


In [17]:
best_model = ""
# results_area
# Comparing both the models 
mae_a = results_area["MAE"].iloc[0]
mae_b = results_b["MAE"].iloc[0]
model_a = "Area Model"
model_b = "Bedroom Model"

    # mae = float(results["MAE"])

if mae_a > mae_b:

    best_model = model_b

elif mae_a < mae_b:
    best_model = model_a

#same performance condition 
if mae_a == mae_b:
    best_model += model_a
    best_model += ","
    best_model += model_b

print(f"Best model as per mae comparison : {best_model}")

Best model as per mae comparison : Area Model


In [18]:
#Revision 2
import pandas as pd
import numpy as np 

In [19]:
#Available data to us
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)
df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [20]:
#Shuffling 

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]



In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [22]:
y_pred = model.predict(X_test)

results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [23]:
print(model.coef_)
print(model.intercept_)

[ 0.11023891 -1.15187713]
-8.74573378839591


In [24]:
#checking the error
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print("MAE :",mae)

MAE : 7.133105802047773


In [25]:
# #Xgboost model 
# from xgboost import XGBRegressor

# model = XGBRegressor(
#     learning_rate = 0.1,
#     max_depth = 5,
#     n_estimators = 50,
#     random_state = 42
# )

# model.fit(X_train,y_train)



In [26]:
y_pred = model.predict(X_test)

mae_xgb = mean_absolute_error(y_test,y_pred)

print("MAE of XGB Model",mae_xgb)

MAE of XGB Model 7.133105802047773


In [27]:
#Revision 3 
import pandas as pd 
import numpy as np

In [28]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [29]:
#shuffling splitting

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [30]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)



In [31]:
print(model.intercept_)
print(model.coef_)

-8.74573378839591
[ 0.11023891 -1.15187713]


In [32]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

In [33]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print(mae)

7.133105802047773


In [34]:
#Revision 4 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [35]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [36]:
#shuffling

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]


In [37]:
model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)



In [38]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [39]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

In [40]:
print(f"MAE of the model :{mean_absolute_error(y_test,y_pred)}")

MAE of the model :7.133105802047773


In [41]:
#Revision 5 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [42]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [43]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]



In [44]:
model = LinearRegression()

model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)



In [45]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [46]:
#results

results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

In [47]:
mae = mean_absolute_error(y_test,y_pred)

print("MAE of the model",mae)

MAE of the model 7.133105802047773


In [48]:
#Revision 6 
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [49]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [50]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]



In [51]:
model = LinearRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)


In [52]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [53]:
#results 
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [54]:
mae = mean_absolute_error(y_test,y_pred)

print(f"MAE : {mae}")

MAE : 7.133105802047773


In [55]:
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [56]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}


df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [57]:
#shuffling and sampling

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]



In [58]:
model = LinearRegression()

model.fit(X_train,y_train)



LinearRegression()

In [59]:
y_pred = model.predict(X_test)



In [60]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [61]:
results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

results

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [62]:
mae = mean_absolute_error(y_test,y_pred)

print(f"MAE for the model trained is : {mae}")

MAE for the model trained is : 7.133105802047773


In [63]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [64]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [65]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index] # stop at 75 % data for training 
df_test = df.iloc[split_index:] # take the other 25% for testing

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]



In [66]:
#Initializing the model 

model = LinearRegression()

In [67]:
#Fitting the model 
model.fit(X_train,y_train)

y_pred = model.predict(X_test)



In [68]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [69]:
#results 
results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

results

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [70]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")



Mean absolute error : 7.133105802047773


In [71]:
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [72]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [73]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [74]:
#Initializing the model

model = LinearRegression()


In [75]:
#Fitting the model
model.fit(X_train,y_train)


LinearRegression()

In [76]:
#Predicting using the model 

y_pred = model.predict(X_test)



In [77]:
#Checking the coefficient and intercept

model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [78]:
#Checking the results

results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

results

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [79]:
#Checking the evalation metrics

mae = mean_absolute_error(y_test,y_pred)

print(f"Mean abosulute error for the model : {mae}")

Mean abosulute error for the model : 7.133105802047773


In [80]:
#Revision 9
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error


In [81]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [82]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']



In [83]:
#Model initialization

model = LinearRegression()


In [84]:
model.fit(X_train,y_train)


LinearRegression()

In [85]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [86]:
y_pred = model.predict(X_test)

In [87]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results 

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [88]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773


In [89]:
#Revision 10
import pandas as pd
import numpy as np 
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression


In [90]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

,area_sqft,bedrooms,price
0,500,1,50
1,700,1,65
2,800,2,75
3,1000,2,90
4,1200,3,120


In [92]:
df.columns.to_list()

df.isna().sum()

area_sqft    0
bedrooms     0
price        0
dtype: int64

In [93]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train['price']

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']


In [94]:
model = LinearRegression()

In [95]:
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [96]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [97]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results 

,Actual,Predicted
0,90,99.189420
1,180,185.076792


In [98]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773
